name: Morning Newspaper
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
jobs:
  build_and_send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y weasyprint
          pip install requests beautifulsoup4 google-genai weasyprint google-api-python-client google-auth feedparser
      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          MY_CHAT_ID: ${{ secrets.MY_CHAT_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python newspaper_bot.py
